theme: minima

title: Juan Martin Cadena
address: West Lafayette, IN 47906
phone: (765) 772-8587
email: cadenaj@purdue.edu
linkedin: juanmartincadena

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
