

title: Juan Martin Cadena
author:
  name: Juan Martin Cadena
  email: cadenaj@purdue.edu
  

address: West Lafayette, IN 47906
phone: (765) 772-8587
linkedin: juanmartincadena

theme: minima

minima:
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/juanmartincadena/" }
    - { platform: github,   user_url: "https://github.com/juanmarcadena" }
    - { platform: instagram, user_url: "https://www.instagram.com/juanmarcadena/" }

