title: Juan Martin Cadena
author:
  name: Juan Martin Cadena
  email: cadenaj@purdue.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.


address: West Lafayette, IN 47906
phone: (765) 772-8587
linkedin: juanmartincadena


# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/juanmartincadena/" }
    - { platform: github,   user_url: "https://github.com/juanmarcadena" }
    - { platform: instagram, user_url: "https://www.instagram.com/juanmarcadena/" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
